// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/extensions/godaddydns/controlv1/control.proto

// Wire contract copied from github.com/gotthboard/gotth-extensions at
// 3822dd722bc8606b8843d0a68c7c3e9f598d9ccc. Only go_package is consumer-local.

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthState int32

const (
	HealthState_HEALTH_STATE_UNSPECIFIED HealthState = 0
	HealthState_HEALTH_STATE_STARTING    HealthState = 1
	HealthState_HEALTH_STATE_READY       HealthState = 2
	HealthState_HEALTH_STATE_DEGRADED    HealthState = 3
	HealthState_HEALTH_STATE_STOPPING    HealthState = 4
	HealthState_HEALTH_STATE_FAILED      HealthState = 5
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "HEALTH_STATE_UNSPECIFIED",
		1: "HEALTH_STATE_STARTING",
		2: "HEALTH_STATE_READY",
		3: "HEALTH_STATE_DEGRADED",
		4: "HEALTH_STATE_STOPPING",
		5: "HEALTH_STATE_FAILED",
	}
	HealthState_value = map[string]int32{
		"HEALTH_STATE_UNSPECIFIED": 0,
		"HEALTH_STATE_STARTING":    1,
		"HEALTH_STATE_READY":       2,
		"HEALTH_STATE_DEGRADED":    3,
		"HEALTH_STATE_STOPPING":    4,
		"HEALTH_STATE_FAILED":      5,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_extensions_godaddydns_controlv1_control_proto_enumTypes[0].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_internal_extensions_godaddydns_controlv1_control_proto_enumTypes[0]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_internal_extensions_godaddydns_controlv1_control_proto_rawDescGZIP(), []int{0}
}

type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Major         uint32                 `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_internal_extensions_godaddydns_controlv1_control_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolVersion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

type InterfaceVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Major         uint32                 `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceVersion) Reset() {
	*x = InterfaceVersion{}
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceVersion) ProtoMessage() {}

func (x *InterfaceVersion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceVersion.ProtoReflect.Descriptor instead.
func (*InterfaceVersion) Descriptor() ([]byte, []int) {
	return file_internal_extensions_godaddydns_controlv1_control_proto_rawDescGZIP(), []int{1}
}

func (x *InterfaceVersion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *InterfaceVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

type HandshakeRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId          string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Challenge              []byte                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	ExpectedExtensionId    string                 `protobuf:"bytes,3,opt,name=expected_extension_id,json=expectedExtensionId,proto3" json:"expected_extension_id,omitempty"`
	ExpectedManifestSha256 string                 `protobuf:"bytes,4,opt,name=expected_manifest_sha256,json=expectedManifestSha256,proto3" json:"expected_manifest_sha256,omitempty"`
	ExpectedGrantSha256    string                 `protobuf:"bytes,5,opt,name=expected_grant_sha256,json=expectedGrantSha256,proto3" json:"expected_grant_sha256,omitempty"`
	ExpectedSessionSha256  string                 `protobuf:"bytes,6,opt,name=expected_session_sha256,json=expectedSessionSha256,proto3" json:"expected_session_sha256,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_internal_extensions_godaddydns_controlv1_control_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *HandshakeRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *HandshakeRequest) GetExpectedExtensionId() string {
	if x != nil {
		return x.ExpectedExtensionId
	}
	return ""
}

func (x *HandshakeRequest) GetExpectedManifestSha256() string {
	if x != nil {
		return x.ExpectedManifestSha256
	}
	return ""
}

func (x *HandshakeRequest) GetExpectedGrantSha256() string {
	if x != nil {
		return x.ExpectedGrantSha256
	}
	return ""
}

func (x *HandshakeRequest) GetExpectedSessionSha256() string {
	if x != nil {
		return x.ExpectedSessionSha256
	}
	return ""
}

type HandshakeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Challenge        []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	ExtensionId      string                 `protobuf:"bytes,2,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	ExtensionVersion string                 `protobuf:"bytes,3,opt,name=extension_version,json=extensionVersion,proto3" json:"extension_version,omitempty"`
	ManifestSha256   string                 `protobuf:"bytes,4,opt,name=manifest_sha256,json=manifestSha256,proto3" json:"manifest_sha256,omitempty"`
	GrantSha256      string                 `protobuf:"bytes,5,opt,name=grant_sha256,json=grantSha256,proto3" json:"grant_sha256,omitempty"`
	SessionSha256    string                 `protobuf:"bytes,6,opt,name=session_sha256,json=sessionSha256,proto3" json:"session_sha256,omitempty"`
	Control          *ProtocolVersion       `protobuf:"bytes,7,opt,name=control,proto3" json:"control,omitempty"`
	Interfaces       []*InterfaceVersion    `protobuf:"bytes,8,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Capabilities     []string               `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_internal_extensions_godaddydns_controlv1_control_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeResponse) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *HandshakeResponse) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *HandshakeResponse) GetExtensionVersion() string {
	if x != nil {
		return x.ExtensionVersion
	}
	return ""
}

func (x *HandshakeResponse) GetManifestSha256() string {
	if x != nil {
		return x.ManifestSha256
	}
	return ""
}

func (x *HandshakeResponse) GetGrantSha256() string {
	if x != nil {
		return x.GrantSha256
	}
	return ""
}

func (x *HandshakeResponse) GetSessionSha256() string {
	if x != nil {
		return x.SessionSha256
	}
	return ""
}

func (x *HandshakeResponse) GetControl() *ProtocolVersion {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *HandshakeResponse) GetInterfaces() []*InterfaceVersion {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *HandshakeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SessionSha256 string                 `protobuf:"bytes,2,opt,name=session_sha256,json=sessionSha256,proto3" json:"session_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_extensions_godaddydns_controlv1_control_proto_rawDescGZIP(), []int{4}
}

func (x *HealthRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *HealthRequest) GetSessionSha256() string {
	if x != nil {
		return x.SessionSha256
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         HealthState            `protobuf:"varint,1,opt,name=state,proto3,enum=gotth.extensions.v1.HealthState" json:"state,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_extensions_godaddydns_controlv1_control_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetState() HealthState {
	if x != nil {
		return x.State
	}
	return HealthState_HEALTH_STATE_UNSPECIFIED
}

func (x *HealthResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_internal_extensions_godaddydns_controlv1_control_proto protoreflect.FileDescriptor

const file_internal_extensions_godaddydns_controlv1_control_proto_rawDesc = "" +
	"\n" +
	"6internal/extensions/godaddydns/controlv1/control.proto\x12\x13gotth.extensions.v1\"Q\n" +
	"\x0fProtocolVersion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05major\x18\x02 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x03 \x01(\rR\x05minor\"R\n" +
	"\x10InterfaceVersion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05major\x18\x02 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x03 \x01(\rR\x05minor\"\xb1\x02\n" +
	"\x10HandshakeRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\fR\tchallenge\x122\n" +
	"\x15expected_extension_id\x18\x03 \x01(\tR\x13expectedExtensionId\x128\n" +
	"\x18expected_manifest_sha256\x18\x04 \x01(\tR\x16expectedManifestSha256\x122\n" +
	"\x15expected_grant_sha256\x18\x05 \x01(\tR\x13expectedGrantSha256\x126\n" +
	"\x17expected_session_sha256\x18\x06 \x01(\tR\x15expectedSessionSha256\"\x9f\x03\n" +
	"\x11HandshakeResponse\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\x12!\n" +
	"\fextension_id\x18\x02 \x01(\tR\vextensionId\x12+\n" +
	"\x11extension_version\x18\x03 \x01(\tR\x10extensionVersion\x12'\n" +
	"\x0fmanifest_sha256\x18\x04 \x01(\tR\x0emanifestSha256\x12!\n" +
	"\fgrant_sha256\x18\x05 \x01(\tR\vgrantSha256\x12%\n" +
	"\x0esession_sha256\x18\x06 \x01(\tR\rsessionSha256\x12>\n" +
	"\acontrol\x18\a \x01(\v2$.gotth.extensions.v1.ProtocolVersionR\acontrol\x12E\n" +
	"\n" +
	"interfaces\x18\b \x03(\v2%.gotth.extensions.v1.InterfaceVersionR\n" +
	"interfaces\x12\"\n" +
	"\fcapabilities\x18\t \x03(\tR\fcapabilities\"]\n" +
	"\rHealthRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12%\n" +
	"\x0esession_sha256\x18\x02 \x01(\tR\rsessionSha256\"\\\n" +
	"\x0eHealthResponse\x126\n" +
	"\x05state\x18\x01 \x01(\x0e2 .gotth.extensions.v1.HealthStateR\x05state\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code*\xad\x01\n" +
	"\vHealthState\x12\x1c\n" +
	"\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATE_STARTING\x10\x01\x12\x16\n" +
	"\x12HEALTH_STATE_READY\x10\x02\x12\x19\n" +
	"\x15HEALTH_STATE_DEGRADED\x10\x03\x12\x19\n" +
	"\x15HEALTH_STATE_STOPPING\x10\x04\x12\x17\n" +
	"\x13HEALTH_STATE_FAILED\x10\x052\xc1\x01\n" +
	"\x10ExtensionControl\x12Z\n" +
	"\tHandshake\x12%.gotth.extensions.v1.HandshakeRequest\x1a&.gotth.extensions.v1.HandshakeResponse\x12Q\n" +
	"\x06Health\x12\".gotth.extensions.v1.HealthRequest\x1a#.gotth.extensions.v1.HealthResponseBVZTgithub.com/gotthboard/gotth-stack/internal/extensions/godaddydns/controlv1;controlv1b\x06proto3"

var (
	file_internal_extensions_godaddydns_controlv1_control_proto_rawDescOnce sync.Once
	file_internal_extensions_godaddydns_controlv1_control_proto_rawDescData []byte
)

func file_internal_extensions_godaddydns_controlv1_control_proto_rawDescGZIP() []byte {
	file_internal_extensions_godaddydns_controlv1_control_proto_rawDescOnce.Do(func() {
		file_internal_extensions_godaddydns_controlv1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_extensions_godaddydns_controlv1_control_proto_rawDesc), len(file_internal_extensions_godaddydns_controlv1_control_proto_rawDesc)))
	})
	return file_internal_extensions_godaddydns_controlv1_control_proto_rawDescData
}

var file_internal_extensions_godaddydns_controlv1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_extensions_godaddydns_controlv1_control_proto_goTypes = []any{
	(HealthState)(0),          // 0: gotth.extensions.v1.HealthState
	(*ProtocolVersion)(nil),   // 1: gotth.extensions.v1.ProtocolVersion
	(*InterfaceVersion)(nil),  // 2: gotth.extensions.v1.InterfaceVersion
	(*HandshakeRequest)(nil),  // 3: gotth.extensions.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 4: gotth.extensions.v1.HandshakeResponse
	(*HealthRequest)(nil),     // 5: gotth.extensions.v1.HealthRequest
	(*HealthResponse)(nil),    // 6: gotth.extensions.v1.HealthResponse
}
var file_internal_extensions_godaddydns_controlv1_control_proto_depIdxs = []int32{
	1, // 0: gotth.extensions.v1.HandshakeResponse.control:type_name -> gotth.extensions.v1.ProtocolVersion
	2, // 1: gotth.extensions.v1.HandshakeResponse.interfaces:type_name -> gotth.extensions.v1.InterfaceVersion
	0, // 2: gotth.extensions.v1.HealthResponse.state:type_name -> gotth.extensions.v1.HealthState
	3, // 3: gotth.extensions.v1.ExtensionControl.Handshake:input_type -> gotth.extensions.v1.HandshakeRequest
	5, // 4: gotth.extensions.v1.ExtensionControl.Health:input_type -> gotth.extensions.v1.HealthRequest
	4, // 5: gotth.extensions.v1.ExtensionControl.Handshake:output_type -> gotth.extensions.v1.HandshakeResponse
	6, // 6: gotth.extensions.v1.ExtensionControl.Health:output_type -> gotth.extensions.v1.HealthResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_extensions_godaddydns_controlv1_control_proto_init() }
func file_internal_extensions_godaddydns_controlv1_control_proto_init() {
	if File_internal_extensions_godaddydns_controlv1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_extensions_godaddydns_controlv1_control_proto_rawDesc), len(file_internal_extensions_godaddydns_controlv1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_extensions_godaddydns_controlv1_control_proto_goTypes,
		DependencyIndexes: file_internal_extensions_godaddydns_controlv1_control_proto_depIdxs,
		EnumInfos:         file_internal_extensions_godaddydns_controlv1_control_proto_enumTypes,
		MessageInfos:      file_internal_extensions_godaddydns_controlv1_control_proto_msgTypes,
	}.Build()
	File_internal_extensions_godaddydns_controlv1_control_proto = out.File
	file_internal_extensions_godaddydns_controlv1_control_proto_goTypes = nil
	file_internal_extensions_godaddydns_controlv1_control_proto_depIdxs = nil
}
