// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/extensions/godaddydns/controlv1/control.proto

// Wire contract copied from github.com/gotthboard/gotth-extensions at
// 3822dd722bc8606b8843d0a68c7c3e9f598d9ccc. Only go_package is consumer-local.

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtensionControl_Handshake_FullMethodName = "/gotth.extensions.v1.ExtensionControl/Handshake"
	ExtensionControl_Health_FullMethodName    = "/gotth.extensions.v1.ExtensionControl/Health"
)

// ExtensionControlClient is the client API for ExtensionControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtensionControlClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type extensionControlClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionControlClient(cc grpc.ClientConnInterface) ExtensionControlClient {
	return &extensionControlClient{cc}
}

func (c *extensionControlClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, ExtensionControl_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionControlClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ExtensionControl_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtensionControlServer is the server API for ExtensionControl service.
// All implementations must embed UnimplementedExtensionControlServer
// for forward compatibility.
type ExtensionControlServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedExtensionControlServer()
}

// UnimplementedExtensionControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtensionControlServer struct{}

func (UnimplementedExtensionControlServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedExtensionControlServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedExtensionControlServer) mustEmbedUnimplementedExtensionControlServer() {}
func (UnimplementedExtensionControlServer) testEmbeddedByValue()                          {}

// UnsafeExtensionControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionControlServer will
// result in compilation errors.
type UnsafeExtensionControlServer interface {
	mustEmbedUnimplementedExtensionControlServer()
}

func RegisterExtensionControlServer(s grpc.ServiceRegistrar, srv ExtensionControlServer) {
	// If the following call panics, it indicates UnimplementedExtensionControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtensionControl_ServiceDesc, srv)
}

func _ExtensionControl_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionControlServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionControl_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionControlServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionControl_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionControlServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionControl_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionControlServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtensionControl_ServiceDesc is the grpc.ServiceDesc for ExtensionControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtensionControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gotth.extensions.v1.ExtensionControl",
	HandlerType: (*ExtensionControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _ExtensionControl_Handshake_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ExtensionControl_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/extensions/godaddydns/controlv1/control.proto",
}
